version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind :8000 --workers 2 StudentResultManagementSystem.wsgi
    labels:
      com.shyftlabs.project: student-result-management-system
    env_file: .env
    volumes:
      - .:/app:z
    ports:
      - "${PORT}:${PORT}"
